dataset_name: anet
train_split: [ 'training' ]
val_split: [ 'validation' ]
dataset: {
  json_file: /data/anet_1.3/annotations/anet1.3_tsp_filtered.json,
  feat_folder: /data/anet_1.3/tsp_features,
  file_prefix: v_,
  file_ext: .npy,
  num_classes: 1,
  input_dim: 512,
  feat_stride: 16,
  num_frames: 16,
  default_fps: 15,
  trunc_thresh: 0.5,
  crop_ratio: [ 0.9, 1.0 ],
  max_seq_len: 768,
}

model: {
  backbone_type: 'DynE',
  fpn_type: identity,
  max_buffer_len_factor: 1.0,
  backbone_arch: [ 2, 2, 5 ],
  n_encoder_win_size: 15,

  regression_range: [ [ 0, 4 ], [ 4, 8 ], [ 8, 16 ], [ 16, 32 ], [ 32, 64 ], [ 64, 10000 ] ],
  embd_dim: 256,
  mlp_dim: 2048,
  fpn_dim: 256,
  head_dim: 512,
  use_abs_pe: True,
  
  input_noise: 0.7,
  k: 1.2,
  init_conv_vars: 0.15,
  
  dyn_head_flag: True,
  dyn_head: {
    tau: 1.5, 
    init_gate: 1.0, 
    type: "GeReTanH" ,
    dyn_type: 'c'
    }, # False
  head_act: 'relu',
  
}
opt: {
  learning_rate: 0.0005,
  eta_min: 0.00005,
  warmup_epochs: 5,
  epochs: 10,
  weight_decay: 0.05,
}
loader: {
  batch_size: 8,
}
train_cfg: {
  init_loss_norm: 400,
  clip_grad_l2norm: 0.4,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
  label_smoothing: 0.1,
}
# similar to THUMOS
test_cfg: {
  voting_thresh: 0.95,
  pre_nms_topk: 2000,
  # max of 200 predictions per video
  max_seg_num: 200,
  min_score: 0.001,
  # score fusion
  multiclass_nms: False,
  nms_sigma: 0.70,
  ext_score_file: ./data/anet/new_3ensemble_uniformerv2_large_only_global_anet_16x10x3.json,
  duration_thresh: 0.1,
}
output_folder: ./ckpt/
