dataset_name: epic
train_split: [ 'training' ]
val_split: [ 'validation' ]
dataset: {
  json_file: /data/epic_kitchens/annotations/epic_kitchens_100_noun.json,
  feat_folder: /data/epic_kitchens/features,
  file_prefix: ~,
  file_ext: .npz,
  num_classes: 300,
  input_dim: 2304,
  feat_stride: 16,
  num_frames: 32,
  default_fps: 30,
  trunc_thresh: 0.3,
  crop_ratio: [ 0.9, 1.0 ],
  max_seq_len: 2304,
}
model: {

  regression_range: [ [ 0, 4 ], [ 2, 8 ], [ 4, 16 ], [ 8, 32 ], [ 16, 64 ], [ 32, 10000 ] ],
  fpn_type: identity,
  max_buffer_len_factor: 4.0,
  n_encoder_win_size: 1,

  mlp_dim: 1024,
  k: 4,

  # n_encoder_win_size: 1,
  # mlp_dim: 768,
  # k: 5,


  dyn_head: {
    budget_loss_lambda: 1.0, 
    tau: 2.0, 
    init_gate: 1.0, 
    type: "GeReTanH" ,
    dyn_type: 'c'
    }, # False
  head_act: 'relu',
  dyn_head_flag: True,
  
  input_noise: 0.000001,
  
}
opt: {
  learning_rate: 0.0002,
  warmup_epochs: 5,
  eta_min: 0.00005,
  epochs: 20,
  weight_decay: 0.05,
}
loader: {
  batch_size: 2,
}
train_cfg: {
  init_loss_norm: 250,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
  label_smoothing: 0.1,
}
test_cfg: {
  pre_nms_topk: 5000,
  max_seg_num: 2000,
  min_score: 0.001,
  nms_sigma: 0.4,
  multiclass_nms: True
}
output_folder: ./ckpt/
