dataset_name: fineaction
train_split: [ 'training' ]
val_split: [ 'validation' ]
dataset: {
  json_file: /data/fineaction_mae_g/annotations/annotations_gt_af.json,
  feat_folder: /data/fineaction_mae_g/fineaction_mae_g,
  file_prefix: ~,
  file_ext: .npy,
  num_classes: 1,
  input_dim: 1408,
  feat_stride: 16,
  num_frames: 16,
  default_fps: 30,
  trunc_thresh: 0.5,
  crop_ratio: [ 0.9, 1.0 ],
  max_seq_len: 2304,
}

model: {
  backbone_type: 'DynE',
  fpn_type: identity,
  max_buffer_len_factor: 1.0,
  backbone_arch: [ 2, 2, 6 ],
  n_encoder_win_size: 15,

  regression_range: [ [ 0, 4 ], [ 4, 8 ], [ 8, 16 ], [ 16, 32 ], [ 32, 64 ], [ 64, 128 ], [ 128, 10000 ] ],
  embd_dim: 256,
  mlp_dim: 2048,
  fpn_dim: 256,
  head_dim: 512,
  use_abs_pe: True,
  
  input_noise: 0.5,
  k: 1.3,
  init_conv_vars: 0.2,
  
  dyn_head_flag: True,
  dyn_head: {
    budget_loss_lambda: 1.0, 
    tau: 1.5, 
    init_gate: 1.0, 
    type: "GeReTanH" ,
    dyn_type: 'c'
    }, # False
  head_act: 'relu',
}

opt: {
  learning_rate: 0.0005,
  eta_min: 0.00005,
  warmup_epochs: 10,
  epochs: 6,
  weight_decay: 0.025,
}
loader: {
  batch_size: 8,
}

train_cfg: {
  init_loss_norm: 400,
  clip_grad_l2norm: 0.4,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
  label_smoothing: 0.1,
}

# similar to THUMOS
test_cfg: {
  voting_thresh: 0.95,
  pre_nms_topk: 2000,
  # max of 200 predictions per video
  max_seg_num: 200,
  min_score: 0.001,
  # score fusion
  multiclass_nms: False,
  nms_sigma: 0.70,
  ext_score_file: ./data/fineaction/new_swinB_1x1x256_views2x3_max_label_avg_prob.json,
  duration_thresh: 0.1,
}
output_folder: ./ckpt_fineaction/
