dataset_name: hacs
train_split: [ 'training' ]
val_split: [ 'validation' ]
dataset: {
  json_file: ./data/hacs/annotations/HACS_segments_v1.1.1_slowfast.json,
  feat_folder: /data/hacs_features,
  file_ext: .pkl,
  num_classes: 200,
  input_dim: 2304,
  feat_stride: 8,
  num_frames: 32,
  default_fps: 15,
  trunc_thresh: 0.5,
  crop_ratio: [ 0.9, 1.0 ],
  max_seq_len: 960,
  backbone_type: 'slowfast',
}
model: {
  fpn_type: identity,
  max_buffer_len_factor: 1.0,
  backbone_arch: [ 2, 2, 5 ],
  n_encoder_win_size: 3,
  regression_range: [ [ 0, 4 ], [ 4, 8 ], [ 8, 16 ], [ 16, 32 ], [ 32, 64 ], [ 64, 10000 ] ],
  embd_dim: 1024,
  mlp_dim: 1024,
  fpn_dim: 1024,
  head_dim: 1024,
  head_kernel_size: 5,

  use_abs_pe: True,
  input_noise: 0.2,
  k: 1.2,
  init_conv_vars: 0.1,

  dyn_head: {budget_loss_lambda: 1.0, tau: 1.5, init_gate: 1.0, type: "GeReTanH", dyn_type: 'c' }, # False
  dyn_head_flag: True,
  head_act: 'relu',

}
opt: {
  learning_rate: 0.0005,
  eta_min: 0.0005,
  warmup_epochs: 7,
  epochs: 4,
  weight_decay: 0.025,
}
loader: {
  batch_size: 8,
}
train_cfg: {
  init_loss_norm: 400,
  clip_grad_l2norm: 0.5,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
  label_smoothing: 0.1,
}

# similar to THUMOS
test_cfg: {
  voting_thresh: 0.95,
  pre_nms_topk: 2000,
  max_seg_num: 250,
  min_score: 0.001,
  nms_sigma: 0.75,
  multiclass_nms: False,
  ext_score_file: ./data/hacs/validation94.32.json,
  # ext_score_file: /workspace/yl_tal/TriDet2rec/tca_uniformerv2_large_only_global_anet_16x10x3.json,
  duration_thresh: 0.1,
  
}
output_folder: ./ckpt/
